Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/Bantrangsuc/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Quanlybanhang.urls')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from .views import duyet_uudai
from .views import delete_uudai
urlpatterns = [
    path('', views.home, name='home'),
    path('quaybanhangs/', views.quaybanhangs, name='quaybanhangs'),
    path('quaybanhang-edit/<str:ma_quay>/', views.quaybanhang_edit, name='quaybanhang-edit'),
    path('quaybanhang-delete/<str:ma_quay>/', views.quaybanhang_delete, name='quaybanhang-delete'),
    path('quaybanhang-new/', views.quaybanhang_new, name='quaybanhang-new'),  
    path('tichdiem/', views.tichdiem, name='tichdiem'),
    path('doanhthu/', views.doanhthu, name='doanhthu'),  # Định nghĩa URL cho Doanh thu
    path('khaibao/', views.khaibao, name='khaibao'),  # Định nghĩa URL cho Doanh thu
    path('dashboard/', views.dashboard, name='dashboard'),  # Định nghĩa URL cho Doanh thu
    path('mualai/', views.mualai, name='mualai'),  # Định nghĩa URL cho Doanh thu
    path('sanpham/', views.sanpham, name='sanpham'),
    path('khuyenmai/', views.khuyenmai, name='khuyenmai'),
    path('khuyenmai/duyet_uudai/<int:id>/', duyet_uudai, name='duyet_uudai'),

    path('quet-barcode/', views.handle_barcode, name='quet_barcode'), 
    path('xu-ly-barcode/', views.handle_barcode, name='handle_barcode'),


    path('nhanviens/', views.nhanviens, name='nhanviens'),
    path('nhanvien-edit/<str:ma_nhan_vien>/', views.nhanvien_delete, name='nhanvien-edit'),
    path('nhanvien-delete/<str:ma_nhan_vien>/', views.nhanvien_delete, name='nhanvien-delete'),



]

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/models.py
from django.db import models

from Quanlybanhang.models import KhachHang

# Create your models here.

class UuDaiKhachHang(models.Model):
    id = models.AutoField(primary_key=True)
    ma_khach_hang = models.CharField(max_length=20)
    phan_tram_chiet_khau = models.DecimalField(max_digits=5, decimal_places=2)
    duoc_duyet = models.BooleanField(default=False)

    def __str__(self):
      return f'Ưu đãi cho khách hàng {self.ma_khach_hang} - Chiết khấu {self.phan_tram_chiet_khau}'
class HoaDon(models.Model):
    so_hoa_don = models.CharField(max_length=100)
    ngay_lap = models.DateTimeField()
    tong_tien = models.DecimalField(max_digits=10, decimal_places=2)
    # Các trường khác

    def __str__(self):
        return self.so_hoa_don
    
class QuayBanHang(models.Model):
    ten_quay = models.CharField(max_length=100)
    vi_tri = models.CharField(max_length=255)
    # Các trường khác

    def __str__(self):
        return self.ten_quay
    
class NhanVien(models.Model):
    ten_nhan_vien = models.CharField(max_length=100)
    chuc_vu = models.CharField(max_length=100)
    # Các trường khác

    def __str__(self):
        return self.ten_nhan_vien
    
class ChiTietHoaDon(models.Model):
    # Định nghĩa các trường dữ liệu ở đây
    hoa_don = models.ForeignKey('HoaDon', on_delete=models.CASCADE)
    san_pham = models.CharField(max_length=100)
    so_luong = models.IntegerField()

    def __str__(self):
        return f"ChiTietHoaDon {self.id}"
    


class SanPham(models.Model):
    ma_san_pham = models.CharField(max_length=20, primary_key=True)
    ten_san_pham = models.CharField(max_length=255)
    gia = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.ten_san_pham

class KhuyenMai(models.Model):
    ma_khuyen_mai = models.CharField(max_length=20, primary_key=True)
    ma_san_pham = models.ForeignKey(SanPham, on_delete=models.CASCADE)
    phan_tram_chiet_khau = models.DecimalField(max_digits=5, decimal_places=2)
    ngay_bat_dau = models.DateTimeField()
    ngay_ket_thuc = models.DateTimeField()

    def __str__(self):
        return f'Khuyến mãi {self.ma_khuyen_mai} - {self.ma_san_pham.ten_san_pham}'

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/forms.py
# home/forms.py
from django import forms
from Quanlybanhang.models import NhanVien  # Hoặc import từ đúng ứng dụng của bạn
from Quanlybanhang.models import UuDaiKhachHang
from Quanlybanhang.models import KhuyenMai  # Correct import


class NhanVienForm(forms.ModelForm):
    class Meta:
        model = NhanVien
        fields = ['ma_nhan_vien', 'ho_ten']


class KhuyenMaiForm(forms.ModelForm):
    class Meta:
        model = KhuyenMai
        fields = '__all__'

class UuDaiKhachHangForm(forms.ModelForm):
    class Meta:
       model = UuDaiKhachHang
       fields = '__all__'

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
from .models import HoaDon, QuayBanHang, NhanVien, ChiTietHoaDon
from Quanlybanhang.models import UuDaiKhachHang, KhachHang, KhuyenMai, SanPham,TichDiem  # Import from Quanlybanhang
from .forms import KhuyenMaiForm, UuDaiKhachHangForm # Import from home
from home.models import KhuyenMai
from django.http import Http404

from django.db.models import Sum, F, Q
from django.template import loader
from django.urls import reverse
from django.contrib import messages
from Quanlybanhang.models import HoaDon
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from Quanlybanhang.models import QuayBanHang
from Quanlybanhang.forms import QuayBanHangForm
from Quanlybanhang.models import NhanVien  # Import model NhanVien
from Quanlybanhang.forms import NhanVienForm  # Import form NhanVienForm
from Quanlybanhang.forms import SanPham  # Import form NhanVienForm
from Quanlybanhang.forms import SanPhamForm  # Import form NhanVienForm
import datetime
from .forms import KhuyenMaiForm, UuDaiKhachHangForm # Import from home

from reportlab.pdfgen.canvas import Canvas

from django.contrib import messages

# Create your views here.
def home(request):
    return render(request, 'home/home.html')

# Trang hiển thị danh sách các quầy bán hàng
def quaybanhangs(request):
    quaybanhangs = QuayBanHang.objects.all()
    template = loader.get_template('home/quaybanhang/quaybanhangs.html')
    context = {
        'active_menu': 'quaybanhangs',
        'cacquaybanhangs': quaybanhangs,  # Truyền danh sách quầy vào context
    }
    return HttpResponse(template.render(context, request))

def sanpham(request):
    # Lấy tất cả các sản phẩm
    san_phams = SanPham.objects.all()
    
    # Sử dụng loader để lấy template
    template = loader.get_template('home/sanpham/sanpham.html')
    
    # Truyền danh sách sản phẩm và active menu vào context
    context = {
        'active_menu': 'sanpham',  # Để làm mục này active trong menu
        'san_phams': san_phams,    # Truyền danh sách sản phẩm vào context
    }
    
    # Render template với context
    return HttpResponse(template.render(context, request))


# Trang chỉnh sửa một quầy bán hàng cụ thể
def quaybanhang_edit(request, ma_quay):
    quaybanhang = get_object_or_404(QuayBanHang, ma_quay=ma_quay)

    # Lấy danh sách nhân viên từ database
    nhanviens = NhanVien.objects.all()
    # Truy vấn danh sách sản phẩm của quầy
    sanphams = quaybanhang.san_phams.all()

    # Tính tổng đơn đã bán (ví dụ)
    # bạn có thể thay thế code này bằng code query đơn hàng của bạn
    tong_don_ban = 123  # ví dụ số đơn đã bán
    form = QuayBanHangForm(instance=quaybanhang)

    if request.method == 'POST':
        form = QuayBanHangForm(request.POST, instance=quaybanhang)
        if form.is_valid():
            try:
                form.save()

                # Xử lý form thay đổi nhân viên phụ trách (nếu có)
                new_nhan_vien_ma = request.POST.get('new_nhan_vien_phu_trach')
                if new_nhan_vien_ma:
                   new_nhan_vien = get_object_or_404(NhanVien, ma_nhan_vien=new_nhan_vien_ma)
                   quaybanhang.nhan_vien_phu_trach = new_nhan_vien
                   quaybanhang.save()
                   messages.success(request, 'Đã thay đổi nhân viên phụ trách thành công!')
                else:
                   messages.error(request, 'Lỗi không tìm thấy nhân viên!')
            except Exception as e:
                print(f"Lỗi khi lưu thông tin quầy: {e}")  # In ra console
                return JsonResponse({'success': False, 'error': str(e)})


            # Xử lý form tạo hóa đơn bán hàng (nếu có)
            ma_hoa_don = request.POST.get('ma_hoa_don')
            ngay_lap = request.POST.get('ngay_lap')
            tong_tien = request.POST.get('tong_tien')
            ma_khach_hang = request.POST.get('ma_khach_hang')
            if ma_hoa_don and ngay_lap and tong_tien and ma_khach_hang:
                try:
                    HoaDon.objects.create(
                        ma_hoa_don=ma_hoa_don,
                        ngay_lap=ngay_lap,
                        tong_tien=tong_tien,
                        ma_khach_hang=ma_khach_hang,
                    )
                    messages.success(request, 'Đã tạo hóa đơn bán hàng thành công!')
                except Exception as e:
                    messages.error(request, f'Lỗi khi tạo hóa đơn bán hàng: {e}')

             # Xử lý form in hóa đơn bán hàng (nếu có)
            ma_hoa_don_in = request.POST.get('ma_hoa_don_in')
            if ma_hoa_don_in:
                 try:
                      hoa_don = get_object_or_404(HoaDon, ma_hoa_don=ma_hoa_don_in)
                     # Tạo file PDF
                      response = HttpResponse(content_type='application/pdf')
                      response['Content-Disposition'] = f'attachment; filename="hoa_don_{ma_hoa_don_in}.pdf"'
                      p = Canvas(response, pagesize=letter)
                      p.drawString(1 * inch, 10.5 * inch, f'Mã hóa đơn: {hoa_don.ma_hoa_don}')
                      p.drawString(1 * inch, 10 * inch, f'Ngày lập: {hoa_don.ngay_lap}')
                      p.drawString(1 * inch, 9.5 * inch, f'Tổng tiền: {hoa_don.tong_tien}')
                      p.drawString(1 * inch, 9 * inch, f'Mã khách hàng: {hoa_don.ma_khach_hang}')
                      p.save()
                      return response
                 except Exception as e:
                      messages.error(request, f'Lỗi khi in hóa đơn bán hàng: {e}')

            # Xử lý form in phiếu bảo hành
            ma_san_pham_bao_hanh = request.POST.get('ma_san_pham_bao_hanh')
            ma_khach_hang_bao_hanh = request.POST.get('ma_khach_hang_bao_hanh')
            if ma_san_pham_bao_hanh and ma_khach_hang_bao_hanh:
                 try:
                    # Tạo file PDF phiếu bảo hành
                    response = HttpResponse(content_type='application/pdf')
                    response['Content-Disposition'] = f'attachment; filename="phieu_bao_hanh_{ma_san_pham_bao_hanh}.pdf"'
                    p = Canvas(response, pagesize=letter)
                    p.drawString(1 * inch, 10.5 * inch, f'Mã sản phẩm: {ma_san_pham_bao_hanh}')
                    p.drawString(1 * inch, 10 * inch, f'Mã khách hàng: {ma_khach_hang_bao_hanh}')
                    p.drawString(1 * inch, 9.5 * inch, 'Thời gian bảo hành: 1 năm')
                    p.save()
                    return response
                 except Exception as e:
                    messages.error(request, f'Lỗi khi in phiếu bảo hành: {e}')

            messages.success(request, 'Đã lưu thông tin quầy thành công!')
            return redirect('quaybanhangs')
        else:
             messages.error(request, 'Lỗi khi lưu thông tin quầy')

    context = {
        'quaybanhang': quaybanhang,
        'nhanviens': nhanviens,
        'sanphams': sanphams,
        'tong_don_ban': tong_don_ban,
        'form': form,
      }
    return render(request, 'home/quaybanhang/quaybanhang-edit.html', context)


def khuyenmai(request):
    khuyen_mai = KhuyenMai.objects.all()
    uudais = UuDaiKhachHang.objects.all()
    sanphams = SanPham.objects.all() # Get list of san phams
    if request.method == 'POST':
        if 'add_company_promotion' in request.POST:
              try:
                ma_khuyen_mai = request.POST.get('ma_khuyen_mai')
                ma_san_pham = request.POST.get('ma_san_pham')
                phan_tram_chiet_khau = request.POST.get('phan_tram_chiet_khau')
                ngay_bat_dau = request.POST.get('ngay_bat_dau')
                ngay_ket_thuc = request.POST.get('ngay_ket_thuc')


                if ma_khuyen_mai and ma_san_pham and phan_tram_chiet_khau and ngay_bat_dau and ngay_ket_thuc:
                    sanpham = get_object_or_404(SanPham, ma_san_pham=ma_san_pham)
                    KhuyenMai.objects.create(
                        ma_khuyen_mai = ma_khuyen_mai,
                        ma_san_pham = sanpham,
                        phan_tram_chiet_khau = phan_tram_chiet_khau,
                        ngay_bat_dau = ngay_bat_dau,
                        ngay_ket_thuc = ngay_ket_thuc
                       )
                    messages.success(request, "Khuyến mãi công ty đã được thêm thành công!")
                    return redirect('khuyenmai')
                else:
                  messages.error(request, 'Vui lòng điền đầy đủ thông tin!')
              except Exception as e:
                messages.error(request, f'Lỗi khi tạo khuyến mãi: {e}')
        elif 'add_customer_discount' in request.POST:
              try:
                   ma_khach_hang = request.POST.get('ma_khach_hang')
                   phan_tram_chiet_khau = request.POST.get('phan_tram_chiet_khau')
                   if ma_khach_hang and phan_tram_chiet_khau:
                      UuDaiKhachHang.objects.create(
                          ma_khach_hang = ma_khach_hang,
                          phan_tram_chiet_khau = phan_tram_chiet_khau
                      )
                      messages.success(request, 'Đã thêm ưu đãi khách hàng thành công!')
                      return redirect('khuyenmai')
                   else:
                     messages.error(request, "Vui lòng điền đầy đủ thông tin!")
              except Exception as e:
                   messages.error(request, f"Lỗi khi thêm ưu đãi khách hàng: {e}")
        
    context = {
        'active_menu': 'khuyenmai',
        'khuyenmais': khuyen_mai,
        'uudais': uudais,
        'sanphams': sanphams,
    }
    return render(request, 'home/khuyenmai/khuyenmai.html', context)


def duyet_uudai(request, id):
    if request.method == "POST":
        uudai = get_object_or_404(UuDaiKhachHang, pk=id)

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/templates/home/nhanvien/nhanvien-delete.html
{% extends "master-page.html" %}

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/templates/home/nhanvien/nhanvien-edit.html
{% extends "master-page.html" %}
{% load static %}

{% comment %} {% block nav-bar %}
    {%include '../includes/nav-bar.html'%}
{% endblock %} {% endcomment %}

{% block left-menu %}
    {%include 'includes/left-menu.html'%}
{% endblock %}

{% block content %}
    <div class="container-xxl flex-grow-1 container-p-y">
        <!-- Input Sizing -->
        <div class="col-md-6">
            <div class="card">
              <h5 class="card-header">Input Sizing & Shape</h5>
              <div class="card-body">
                <small class="text-light fw-medium">Input text</small>

                <div class="mt-2 mb-4">
                  <label for="largeInput" class="form-label">Large input</label>
                  <input
                    id="largeInput"
                    class="form-control form-control-lg"
                    type="text"
                    placeholder=".form-control-lg" />
                </div>
                <div class="mb-4">
                  <label for="defaultInput" class="form-label">Default input</label>
                  <input id="defaultInput" class="form-control" type="text" placeholder="Default input" />
                </div>
                <div>
                  <label for="smallInput" class="form-label">Small input</label>
                  <input
                    id="smallInput"
                    class="form-control form-control-sm"
                    type="text"
                    placeholder=".form-control-sm" />
                </div>
              </div>
              <hr class="m-0" />
              <div class="card-body">
                <small class="text-light fw-medium">Input select</small>
                <div class="mt-2 mb-4">
                  <label for="largeSelect" class="form-label">Large select</label>
                  <select id="largeSelect" class="form-select form-select-lg">
                    <option>Large select</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                  </select>
                </div>
                <div class="mb-4">
                  <label for="defaultSelect" class="form-label">Default select</label>
                  <select id="defaultSelect" class="form-select">
                    <option>Default select</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                  </select>
                </div>
                <div>
                  <label for="smallSelect" class="form-label">Small select</label>
                  <select id="smallSelect" class="form-select form-select-sm">
                    <option>Small select</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                  </select>
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
          </div>
    </div>
{% endblock %}

{% block footer %}
    {%include 'includes/footer.html'%}
{% endblock %}

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/templates/home/nhanvien/nhanvien-new.html
{% extends "master-page.html" %}
{% block left-menu %}
    {% include 'includes/left-menu.html' %}
{% endblock %}


{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Quầy Bán Hàng/</span> Mới</h4>
    <div>
        <div class="row">
            <div class="col-xl">
                <div class="card mb-6">
                  <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Basic Layout</h5>
                    <small class="text-body float-end">Default label</small>
                  </div>
                  <div class="card-body">
                    <form>
                      <div class="mb-6">
                        <label class="form-label" for="basic-default-fullname">Full Name</label>
                        <input type="text" class="form-control" id="basic-default-fullname" placeholder="John Doe">
                      </div>
                      <div class="mb-6">
                        <label class="form-label" for="basic-default-company">Company</label>
                        <input type="text" class="form-control" id="basic-default-company" placeholder="ACME Inc.">
                      </div>
                      <div class="mb-6">
                        <label class="form-label" for="basic-default-email">Email</label>
                        <div class="input-group input-group-merge">
                          <input type="text" id="basic-default-email" class="form-control" placeholder="john.doe" aria-label="john.doe" aria-describedby="basic-default-email2">
                          <span class="input-group-text" id="basic-default-email2">@example.com</span>
                        </div>
                        <div class="form-text">You can use letters, numbers &amp; periods</div>
                      </div>
                      <div class="mb-6">
                        <label class="form-label" for="basic-default-phone">Phone No</label>
                        <input type="text" id="basic-default-phone" class="form-control phone-mask" placeholder="658 799 8941">
                      </div>
                      <div class="mb-6">
                        <label class="form-label" for="basic-default-message">Message</label>
                        <textarea id="basic-default-message" class="form-control" placeholder="Hi, Do you have a moment to talk Joe?"></textarea>
                      </div>
                      <button type="submit" class="btn btn-primary">Send</button>
                    </form>
                  </div>
                </div>
              </div>
    </div>
</div>
{% endblock %}

{% block footer %}
    {% include 'includes/footer.html' %}
{% endblock %}

Python - Copy/CUAHANGTRANGSUC/Cuahangtrangsuc/home/templates/home/nhanvien/nhanviens.html
{% extends "master-page.html" %}
{% load static %}

{% block nav-bar %}
    {%include 'includes/nav-bar.html'%}
{% endblock %} 

{% block left-menu %}
    {% include 'includes/left-menu.html' %}
{% endblock %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Quản lý /</span> Nhân Viên
    </h4>

    <div class="row">
        {% for nhanvien in nhanviens %}
        <div class="col-md-6 col-lg-4 mb-4">
            <div class="card h-100">
                 <div class="card-body">
                     <div class="d-flex align-items-start align-items-sm-center gap-4">
                        <div class="avatar me-4">
                               <img src="{% static 'home/assets/img/avatars/1.png' %}" alt="user-avatar" class="d-block rounded" height="100" width="100" id="uploadedAvatar" />
                         </div>
                        <div class="d-flex flex-column">
                            <h5 class="mb-2 text-capitalize">{{ nhanvien.ho_ten }}</h5>
                            <p class="text-muted mb-1"><i class="bx bx-id-card bx-sm me-1"></i>Mã NV: {{ nhanvien.ma_nhan_vien }}</p>
                           
                            <div class="d-flex align-items-center">
                            <i class="bx bxs-store bx-sm text-primary me-1"></i>
                            <span class="text-muted ">
                                {% if nhanvien.quaybanhang_set.first %}
                                    {{ nhanvien.quaybanhang_set.first.ten_quay }}
                                {% else %}
                                    <span class="badge bg-label-warning">Chưa phân công</span>
                                {% endif %}
                            </span>
                            </div>
                        </div>
                     </div>
                   
                </div>
                  <div class="card-footer bg-transparent border-top d-flex justify-content-end">
                         <div class="dropdown">
                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                    <i class="bx bx-dots-vertical-rounded"></i>
                                </button>
                                <div class="dropdown-menu">
                                     <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#editEmployeeModal{{ nhanvien.ma_nhan_vien }}">
                                        <i class="bx bx-edit me-1"></i> Chỉnh sửa
                                     </button>

                                      <form method="post" action="{% url 'nhanvien-delete' nhanvien.ma_nhan_vien %}">
                                           {% csrf_token %}
                                        <button type="submit" class="dropdown-item"><i class="bx bx-trash me-1"></i> Xóa</button>
                                     </form>
                                </div>
                            </div>
                    </div>
            </div>
        </div>
         <div class="modal fade" id="editEmployeeModal{{ nhanvien.ma_nhan_vien }}" tabindex="-1" aria-labelledby="editEmployeeModalLabel{{ nhanvien.ma_nhan_vien }}" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editEmployeeModalLabel{{ nhanvien.ma_nhan_vien }}">Chỉnh sửa nhân viên</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                 </div>
               <div class="modal-body">
                  <form method="post" id="editEmployeeForm{{ nhanvien.ma_nhan_vien }}">
                        {% csrf_token %}
                       <div class="mb-3">
                            <label for="maNhanVienEdit{{ nhanvien.ma_nhan_vien }}" class="form-label">Mã nhân viên</label>
                            <input type="text" class="form-control" id="maNhanVienEdit{{ nhanvien.ma_nhan_vien }}" name="ma_nhan_vien" value="{{ nhanvien.ma_nhan_vien }}" required>
                        </div>
                         <div class="mb-3">
                            <label for="hoTenEdit{{ nhanvien.ma_nhan_vien }}" class="form-label">Họ và tên</label>
                            <input type="text" class="form-control" id="hoTenEdit{{ nhanvien.ma_nhan_vien }}" name="ho_ten" value="{{ nhanvien.ho_ten }}" required>
                         </div>
                         <input type="hidden" name="edit_employee" value="true">
                     </form>
                </div>
                <div class="modal-footer">
                     <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Hủy</button>
                    <button type="submit" form="editEmployeeForm{{ nhanvien.ma_nhan_vien }}" class="btn btn-primary">Lưu thay đổi</button>
                </div>
           </div>
        </div>
     </div>
        {% empty %}
            <div class="col-12 text-center">
                <p>Không có nhân viên nào.</p>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-end mt-3 me-3">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addEmployeeModal">
            <i class="bx bx-plus-circle me-1"></i> Thêm nhân viên
        </button>
    </div>
</div>

<div class="modal fade" id="addEmployeeModal" tabindex="-1" aria-labelledby="addEmployeeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addEmployeeModalLabel">Thêm nhân viên mới</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="addEmployeeForm">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="maNhanVien" class="form-label">Mã nhân viên</label>
                        <input type="text" class="form-control" id="maNhanVien" name="ma_nhan_vien" required>
                    </div>
                     <div class="mb-3">
                        <label for="hoTen" class="form-label">Họ và tên</label>
                        <input type="text" class="form-control" id="hoTen" name="ho_ten" required>
                     </div>
                     <input type="hidden" name="add_employee" value="true">
                </form>
            </div>
            <div class="modal-footer">
                 <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Hủy</button>
                <button type="submit" form="addEmployeeForm" class="btn btn-primary">Lưu</button>
             </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
    {%include 'includes/footer.html'%}
{% endblock %}